project_id = "app-de-suplementos"

[api]
enabled = true
port = 55321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55322
shadow_port = 55320
major_version = 15

[db.migrations]
enabled = true

[db.seed]
enabled = false

[studio]
enabled = true
port = 55323
api_url = "http://127.0.0.1"

[inbucket]
enabled = false

[storage]
enabled = true
file_size_limit = "5MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["http://localhost:5173"]
jwt_expiry = 3600
enable_signup = false
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
policy = "per_worker"

[analytics]
enabled = false
